// Mock data for demo mode
import api from './api';

export const MOCK_CHATS = [
    {
        id: '1',
        name: 'General Chat',
        last_message: 'Hello! How can I help you today?',
        last_message_time: new Date().toISOString(),
        ai_enabled: true
    },
    {
        id: '2',
        name: 'Project Discussion',
        last_message: 'Let\'s discuss the frontend implementation',
        last_message_time: new Date(Date.now() - 3600000).toISOString(),
        ai_enabled: false
    },
    {
        id: '3',
        name: 'AI Assistant',
        last_message: 'I\'m here to help with your questions!',
        last_message_time: new Date(Date.now() - 7200000).toISOString(),
        ai_enabled: true
    }
];

export const MOCK_MESSAGES = {
    '1': [
        {
            id: 'm1',
            chat_id: '1',
            sender_id: '1',
            content: 'Hi! This is a demo of ChatIA',
            timestamp: new Date(Date.now() - 300000).toISOString()
        },
        {
            id: 'm2',
            chat_id: '1',
            sender_id: 'AI',
            content: 'Hello! Welcome to ChatIA demo mode. This is a frontend-only version showing the UI design. In production, this would connect to a backend with AI integration.',
            timestamp: new Date(Date.now() - 240000).toISOString()
        },
        {
            id: 'm3',
            chat_id: '1',
            sender_id: '1',
            content: 'How does this work?',
            timestamp: new Date(Date.now() - 180000).toISOString()
        },
        {
            id: 'm4',
            chat_id: '1',
            sender_id: 'AI',
            content: 'This is a mock interface demonstrating the chat functionality. You can send messages, toggle AI, and see the UI in action. In the full version, AI responses would be generated by Gemini API.',
            timestamp: new Date(Date.now() - 120000).toISOString()
        }
    ],
    '2': [
        {
            id: 'm5',
            chat_id: '2',
            sender_id: '1',
            content: 'Let\'s work on the frontend',
            timestamp: new Date(Date.now() - 3600000).toISOString()
        },
        {
            id: 'm6',
            chat_id: '2',
            sender_id: '2',
            content: 'Sounds good! What should we start with?',
            timestamp: new Date(Date.now() - 3500000).toISOString()
        }
    ],
    '3': [
        {
            id: 'm7',
            chat_id: '3',
            sender_id: 'AI',
            content: 'Hello! I\'m your AI assistant. How can I help you today?',
            timestamp: new Date(Date.now() - 7200000).toISOString()
        }
    ]
};

// Helper to get messages for a chat
export const getMessagesForChat = (chatId) => {
    return MOCK_MESSAGES[chatId] || [];
};

// Helper to add a message (stored in localStorage)
export const addMessage = (chatId, content, imageUrl = null, userId = null) => {
    const newMessage = {
        id: `m${Date.now()}`,
        chat_id: chatId,
        sender_id: userId || 'USER', // Use passed userId or 'USER' as fallback
        content: content,
        image_url: imageUrl,
        timestamp: new Date().toISOString()
    };

    const storageKey = `chatia_messages_${chatId}`;
    const existingMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
    const updatedMessages = [...existingMessages, newMessage];
    localStorage.setItem(storageKey, JSON.stringify(updatedMessages));

    // Generate AI response if AI is enabled
    const chat = MOCK_CHATS.find(c => c.id === chatId);
    if (chat && chat.ai_enabled && content.trim()) {
        console.log('Sending message to AI:', content);
        // Call backend to get Gemini response
        api.post('/chat/message', {
            message: content,
            chat_id: chatId
        })
        .then(response => {
            console.log('AI response received:', response.data);
            const aiResponse = {
                id: `m${Date.now()}`,
                chat_id: chatId,
                sender_id: 'AI',
                content: response.data.response,
                timestamp: new Date().toISOString()
            };
            const currentMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
            localStorage.setItem(storageKey, JSON.stringify([...currentMessages, aiResponse]));
        })
        .catch(error => {
            console.error('Error getting AI response:', error);
            console.error('Error details:', error.response?.data);
            // Fallback to error message with details
            const errorMsg = error.response?.data?.error || 'Error desconocido al generar la respuesta';
            const aiResponse = {
                id: `m${Date.now()}`,
                chat_id: chatId,
                sender_id: 'AI',
                content: `⚠️ Error: ${errorMsg}`,
                timestamp: new Date().toISOString()
            };
            const currentMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
            localStorage.setItem(storageKey, JSON.stringify([...currentMessages, aiResponse]));
        });
    }

    return newMessage;
};

// Get all messages including those stored in localStorage
export const getAllMessagesForChat = (chatId) => {
    const baseMessages = MOCK_MESSAGES[chatId] || [];
    const storageKey = `chatia_messages_${chatId}`;
    const storedMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
    return [...baseMessages, ...storedMessages];
};

// Create a new chat
export const createChat = (name) => {
    const newChat = {
        id: `${Date.now()}`,
        name: name,
        last_message: '',
        last_message_time: new Date().toISOString(),
        ai_enabled: true
    };

    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    customChats.push(newChat);
    localStorage.setItem(storageKey, JSON.stringify(customChats));

    return newChat;
};

// Get all chats
export const getAllChats = () => {
    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    return [...MOCK_CHATS, ...customChats];
};
