// Mock data for demo mode
import api from './api';

export const MOCK_CHATS = [
    {
        id: '1',
        name: 'General Chat',
        last_message: 'Hello! How can I help you today?',
        last_message_time: new Date().toISOString(),
        ai_enabled: true
    },
    {
        id: '2',
        name: 'Project Discussion',
        last_message: 'Let\'s discuss the frontend implementation',
        last_message_time: new Date(Date.now() - 3600000).toISOString(),
        ai_enabled: false
    },
    {
        id: '3',
        name: 'AI Assistant',
        last_message: 'I\'m here to help with your questions!',
        last_message_time: new Date(Date.now() - 7200000).toISOString(),
        ai_enabled: true
    }
];

export const MOCK_MESSAGES = {
    '1': [
        {
            id: 'm1',
            chat_id: '1',
            sender_id: '1',
            content: 'Hi! This is a demo of ChatIA',
            timestamp: new Date(Date.now() - 300000).toISOString()
        },
        {
            id: 'm2',
            chat_id: '1',
            sender_id: 'AI',
            content: 'Hello! Welcome to ChatIA demo mode. This is a frontend-only version showing the UI design. In production, this would connect to a backend with AI integration.',
            timestamp: new Date(Date.now() - 240000).toISOString()
        },
        {
            id: 'm3',
            chat_id: '1',
            sender_id: '1',
            content: 'How does this work?',
            timestamp: new Date(Date.now() - 180000).toISOString()
        },
        {
            id: 'm4',
            chat_id: '1',
            sender_id: 'AI',
            content: 'This is a mock interface demonstrating the chat functionality. You can send messages, toggle AI, and see the UI in action. In the full version, AI responses would be generated by Gemini API.',
            timestamp: new Date(Date.now() - 120000).toISOString()
        }
    ],
    '2': [
        {
            id: 'm5',
            chat_id: '2',
            sender_id: '1',
            content: 'Let\'s work on the frontend',
            timestamp: new Date(Date.now() - 3600000).toISOString()
        },
        {
            id: 'm6',
            chat_id: '2',
            sender_id: '2',
            content: 'Sounds good! What should we start with?',
            timestamp: new Date(Date.now() - 3500000).toISOString()
        }
    ],
    '3': [
        {
            id: 'm7',
            chat_id: '3',
            sender_id: 'AI',
            content: 'Hello! I\'m your AI assistant. How can I help you today?',
            timestamp: new Date(Date.now() - 7200000).toISOString()
        }
    ]
};

// Helper to get messages for a chat
export const getMessagesForChat = (chatId) => {
    return MOCK_MESSAGES[chatId] || [];
};

// Helper to add a message (stored in localStorage)
export const addMessage = (chatId, content, imageUrl = null, userId = null) => {
    const newMessage = {
        id: `m${Date.now()}`,
        chat_id: chatId,
        sender_id: userId || 'USER', // Use passed userId or 'USER' as fallback
        content: content,
        image_url: imageUrl,
        timestamp: new Date().toISOString()
    };

    const storageKey = `chatia_messages_${chatId}`;
    const existingMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
    const updatedMessages = [...existingMessages, newMessage];
    localStorage.setItem(storageKey, JSON.stringify(updatedMessages));

    // Generate AI response if AI is enabled
    const allChats = getAllChats();
    const chat = allChats.find(c => c.id === chatId);
    console.log('Chat found:', chat);
    console.log('AI enabled:', chat?.ai_enabled);
    console.log('Content:', content.trim());

    if (chat && chat.ai_enabled && content.trim()) {
        console.log('✅ Sending message to AI:', content);
        console.log('API URL:', '/chat/message');

        // Call backend to get Gemini response
        api.post('/chat/message', {
            message: content,
            chat_id: chatId
        })
        .then(response => {
            console.log('✅ AI response received:', response.data);
            const aiResponse = {
                id: `m${Date.now()}`,
                chat_id: chatId,
                sender_id: 'AI',
                content: response.data.response,
                timestamp: new Date().toISOString()
            };
            const currentMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
            localStorage.setItem(storageKey, JSON.stringify([...currentMessages, aiResponse]));
        })
        .catch(error => {
            console.error('❌ Error getting AI response:', error);
            console.error('❌ Error details:', error.response?.data);
            console.error('❌ Error status:', error.response?.status);
            console.error('❌ Full error:', error);

            // Fallback to error message with details
            const errorMsg = error.response?.data?.error || error.message || 'Error desconocido al generar la respuesta';
            const aiResponse = {
                id: `m${Date.now()}`,
                chat_id: chatId,
                sender_id: 'AI',
                content: `⚠️ Error: ${errorMsg}`,
                timestamp: new Date().toISOString()
            };
            const currentMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
            localStorage.setItem(storageKey, JSON.stringify([...currentMessages, aiResponse]));
        });
    } else {
        console.log('⚠️ Not calling AI because:', {
            chatFound: !!chat,
            aiEnabled: chat?.ai_enabled,
            hasContent: !!content.trim()
        });
    }

    return newMessage;
};

// Get all messages including those stored in localStorage
export const getAllMessagesForChat = (chatId) => {
    const baseMessages = MOCK_MESSAGES[chatId] || [];
    const storageKey = `chatia_messages_${chatId}`;
    const storedMessages = JSON.parse(localStorage.getItem(storageKey) || '[]');
    return [...baseMessages, ...storedMessages];
};

// Create a new chat
export const createChat = (name) => {
    const newChat = {
        id: `${Date.now()}`,
        name: name,
        last_message: '',
        last_message_time: new Date().toISOString(),
        ai_enabled: true
    };

    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    customChats.push(newChat);
    localStorage.setItem(storageKey, JSON.stringify(customChats));

    return newChat;
};

// Get all chats
export const getAllChats = () => {
    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    return [...MOCK_CHATS, ...customChats];
};

// Delete a chat
export const deleteChat = (chatId) => {
    // Don't allow deleting mock chats (predefined chats)
    const isMockChat = MOCK_CHATS.some(c => c.id === chatId);
    if (isMockChat) {
        throw new Error('Cannot delete predefined chats');
    }

    // Remove from custom chats
    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    const updatedChats = customChats.filter(c => c.id !== chatId);
    localStorage.setItem(storageKey, JSON.stringify(updatedChats));

    // Remove messages for this chat
    const messagesKey = `chatia_messages_${chatId}`;
    localStorage.removeItem(messagesKey);

    return true;
};

// Update AI state for a chat
export const updateChatAIState = (chatId, aiEnabled) => {
    // Check if it's a mock chat
    const mockChat = MOCK_CHATS.find(c => c.id === chatId);
    if (mockChat) {
        mockChat.ai_enabled = aiEnabled;
        return;
    }

    // Otherwise, update in custom chats
    const storageKey = 'chatia_custom_chats';
    const customChats = JSON.parse(localStorage.getItem(storageKey) || '[]');
    const chat = customChats.find(c => c.id === chatId);
    if (chat) {
        chat.ai_enabled = aiEnabled;
        localStorage.setItem(storageKey, JSON.stringify(customChats));
    }
};
